INSERT INTO ARTIST(ARTIST_NAME, ARTIST_ID, GENRE)
SELECT *
FROM CSVREAD('classpath:artists.csv');

INSERT INTO TRACK(DANCEABILITY ,ENERGY ,TRACK_KEY ,LOUDNESS ,MODE ,SPEECHINESS ,ACOUSTICNESS,INSTRUMENTALNESS ,LIVENESS ,VALENCE ,TEMPO ,DURATION_MS ,EXPLICIT ,POPULARITY ,TRACK_NAME ,TRACK_ARTIST ,TRACK_ID)
SELECT *
FROM CSVREAD('classpath:unpopular_songs.csv');