INSERT INTO SONG(DANCEABILITY ,ENERGY ,SONG_KEY ,LOUDNESS ,MODE ,SPEECHINESS ,ACOUSTINESS,INSTRUMENTALNESS ,LIVENESS ,VALENCE ,TEMPO ,DURATION_MS ,EXPLICIT ,POPULARITY ,TRACK_NAME ,TRACK_ARTIST ,TRACK_ID)
SELECT *
FROM CSVREAD('unpopular_songs.csv');